### ISSUE TITLE
Implement Edit questions/comments

### ISSUE THREAD

**Issue by aksuman055** [Upvision/community-back-end#6]
part of [Upvision/community-front-end#4](https://github.com/Upvision/community-front-end/issues/4)

**Comment by Navneet-Singh-123** [comment]
Hello Sir, Can I work on this issue ?

**Comment by aksuman055** [comment]
@Navneet-Singh-123 yes, you can go with this, I have assigned you this issue and  remember to work on a separate branch from master.

**Comment by Navneet-Singh-123** [comment]
ok sir

**Comment by aksuman055** [comment]
@Navneet-Singh-123 can you implement the same for front end also?

**Comment by Navneet-Singh-123** [comment]
Yes sir sure. I'll try completing this by tomorrow or day after then I'll proceed with its front end.

**Comment by aksuman055** [comment]
Done with api and now left with the front end implementation.
